### ISSUE TITLE
write() panics if buf.len() == 0

### ISSUE THREAD

**Issue by abaumhauer** [jeromefroe/circbuf-rs#1]
If one attempts to write a zero sized buffer a panic occurs with 'tests::read_and_write_bytes' panicked at 'index out of bounds: the len is 0 but the index is 0'

The following patch and test corrects this issue by returning Ok(0) if the write is empty.

diff --git a/src/lib.rs b/src/lib.rs
index 8d4ba40..0baa6b5 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -503,7 +503,7 @@ impl io::Write for CircBuf {
     fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
         let avail = self.avail();
 
-        if avail == 0 {
+        if avail == 0 || buf.len() == 0 {
             return Ok(0);
         }
 
@@ -680,6 +680,7 @@ mod tests {
     fn read_and_write_bytes() {
         let mut c = CircBuf::with_capacity(8).unwrap();
 
+        assert_eq!(c.write(b"").unwrap(), 0);
         assert_eq!(c.write(b"foo").unwrap(), 3);
         assert_eq!(c.write(b"bar").unwrap(), 3);

**Comment by jeromefroe** [comment]
Thanks for the patch! I just pushed a commit to apply your fix and cut a new release, `0.1.4`, with the changes.
